const AST_NODE_TYPES = {
  JSXElement: 'JSXElement',
  JSXText: 'JSXText',
  JSXExpressionContainer: 'JSXExpressionContainer',
  JSXEmptyExpression: 'JSXEmptyExpression',
  StringLiteral: 'StringLiteral'
};

const FLUENT_ATTRS = {
  attrs: 'attrs',
  l10nId: 'l10nId',
  l10nVars: 'l10nVars',
  l10nJSX: 'l10nJSX'
};

const STANDARD_ELEMENT_TYPES = {
  A: {},
  Abbr: {},
  Address: {},
  Article: {},
  Aside: {},
  B: {},
  Bdi: {},
  Bdo: {},
  Blockquote: {},
  Button: {},
  Body: {},
  Caption: {},
  Cite: {},
  Div: {},
  Data: {},
  Dd: {},
  Del: {},
  Details: {},
  Dfn: {},
  Dl: {},
  Dt: {},
  Fieldset: {},
  Figcaption: {},
  Figure: {},
  Footer: {},
  Form: {},
  H1: {},
  H2: {},
  H3: {},
  H4: {},
  H5: {},
  H6: {},
  Header: {},
  I: {},
  Img: { alt: true },
  Input: { placeholder: true },
  Ins: {},
  Kbd: {},
  Label: {},
  Legend: {},
  Li: {},
  Main: {},
  Mark: {},
  Meter: {},
  Nav: {},
  Noscript: {},
  Optgroup: { label: true },
  Option: {},
  Output: {},
  P: {},
  Pre: {},
  Progress: {},
  Q: {},
  S: {},
  Samp: {},
  Section: {},
  Select: {},
  Small: {},
  Span: {},
  Strong: {},
  Sub: {},
  Summary: {},
  Sup: {},
  Td: {},
  Template: {},
  Textarea: { placeholder: true },
  Th: {},
  Time: { datetime: true },
  Title: {},
  Tr: {},
  U: {},
  Ul: {},
  Var: {},
  Video: {}
};

module.exports = {
  STANDARD_ELEMENT_TYPES,
  FLUENT_ATTRS,
  AST_NODE_TYPES
}