export const AST_NODE_TYPES = {
  JSXElement: 'JSXElement',
  JSXText: 'JSXText',
  JSXExpressionContainer: 'JSXExpressionContainer',
  JSXEmptyExpression: 'JSXEmptyExpression',
  StringLiteral: 'StringLiteral'
};

export const FLUENT_ATTRS = {
  attrs: 'attrs',
  l10nId: 'l10nId',
  l10nVars: 'l10nVars',
  l10nJSX: 'l10nJSX'
};

export const STANDARD_ELEMENT_TYPES = {
  a: {},
  abbr: {},
  address: {},
  article: {},
  aside: {},
  b: {},
  bdi: {},
  bdo: {},
  blockquote: {},
  button: {},
  body: {},
  caption: {},
  cite: {},
  div: {},
  data: {},
  dd: {},
  del: {},
  details: {},
  dfn: {},
  dl: {},
  dt: {},
  fieldset: {},
  figcaption: {},
  figure: {},
  footer: {},
  form: {},
  h1: {},
  h2: {},
  h3: {},
  h4: {},
  h5: {},
  h6: {},
  header: {},
  i: {},
  img: { alt: true },
  input: { placeholder: true },
  ins: {},
  kbd: {},
  label: {},
  legend: {},
  li: {},
  main: {},
  mark: {},
  meter: {},
  nav: {},
  noscript: {},
  optgroup: { label: true },
  option: {},
  output: {},
  p: {},
  pre: {},
  progress: {},
  q: {},
  s: {},
  samp: {},
  section: {},
  select: {},
  small: {},
  span: {},
  strong: {},
  sub: {},
  summary: {},
  sup: {},
  td: {},
  template: {},
  textarea: { placeholder: true },
  th: {},
  time: { datetime: true },
  title: {},
  tr: {},
  u: {},
  ul: {},
  var: {},
  video: {}
};
